config/routes.rb
Rails.application.routes.draw do
  resources :confirmed_orders
  resources :photos
  resources :reviews
  resources :sessions
  
  
  resources :categories
  resources :foods
  resources :bussinesses
  resources :orders
  resources :orderlines
  resources :users
  
  resources :bussinesses do
      collection do
        get 'search'
      end
      resources :reviews
    end
    
  get 'home/index'
  root :to => "home#index"
  get '/bussinesses' => "bussinesses#index"
  get '/about' => "about#index"
  get 'Login' => 'sessions#new', as: :login
  get 'SignUp' => 'users#new', as: :signup
  post 'SignUp' => 'users#create'
  get 'edit_user' => 'users#show', as: :show

  delete 'visitors/index' => 'sessions#destroy', as: :logout

  resources :users do
        get :make_admin, on: :member
  end

  

end

app/models/bussiness.rb
class Bussiness < ActiveRecord::Base
  has_many :foods 
  belongs_to :user
  has_many :photos
  has_many :reviews
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :foods
end

app/models/confirmed_order.rb
class ConfirmedOrder < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :bussiness
  belongs_to :category 
  def self.search(search)
  	where("category_id LIKE ?","%#{search}")
  end
  def self.search2(search)
  	where("bussiness_id LIKE ?","%#{search}")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
  
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  has_one :order
  belongs_to :confirmed_order
  belongs_to :food
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bussiness
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :bussiness
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bussiness
  has_many :orders
  has_many :reviews
  has_secure_password
  
  validates :fname, :lname,:password,:password_confirmation,  presence: true
  validates_format_of :fname, :lname, with: /\A[A-Z]{1}[a-z]+( +[a-zA-Z]+)*/

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

	before_save { self.email = email.downcase }

  
  validates :password, length: { minimum: 6 }
  

end

app/controllers/bussinesses_controller.rb
class BussinessesController < ApplicationController
  before_action :set_bussiness, only: [:show, :edit, :update, :destroy]

  # GET /bussinesses
  # GET /bussinesses.json
  def index
    @bussinesses = Bussiness.all
  end

  # GET /bussinesses/1
  # GET /bussinesses/1.json
  def show
  end

  # GET /bussinesses/new
  def new
    @bussiness = Bussiness.new
  end

  # GET /bussinesses/1/edit
  def edit
  end

  # POST /bussinesses
  # POST /bussinesses.json
  def create
    @bussiness = Bussiness.new(bussiness_params)

    respond_to do |format|
      if @bussiness.save
        format.html { redirect_to @bussiness, notice: 'Bussiness was successfully created.' }
        format.json { render :show, status: :created, location: @bussiness }
      else
        format.html { render :new }
        format.json { render json: @bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bussinesses/1
  # PATCH/PUT /bussinesses/1.json
  def update
    respond_to do |format|
      if @bussiness.update(bussiness_params)
        format.html { redirect_to @bussiness, notice: 'Bussiness was successfully updated.' }
        format.json { render :show, status: :ok, location: @bussiness }
      else
        format.html { render :edit }
        format.json { render json: @bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bussinesses/1
  # DELETE /bussinesses/1.json
  def destroy
    @bussiness.destroy
    respond_to do |format|
      format.html { redirect_to bussinesses_url, notice: 'Bussiness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private 
  
    def admin_only
      if !current_user.admin?
        redirect_to root_path
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bussiness
      @bussiness = Bussiness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bussiness_params
      params.require(:bussiness).permit(:user_id, :name, :ratings, :reviews, :imgs, :instalink, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bussinesses_helper.rb
module BussinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def current_order
  		Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
	  	order = Order.create
	  	session[:order_id] = order.id
	  	order
  	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
      session[:user_id] = user.id
	end
	
	def current_user
      @current_user ||= User.find_by(id: session[:user_id])
	end
    
    def logged_in?
      !current_user.nil?
	end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bussinesses/_form.html.erb
<%= form_for(@bussiness) do |f| %>
  <% if @bussiness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bussiness.errors.count, "error") %> prohibited this bussiness from being saved:</h2>

      <ul>
      <% @bussiness.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ratings %><br>
    <%= f.text_field :ratings %>
  </div>
  <div class="field">
    <%= f.label :reviews %><br>
    <%= f.text_area :reviews %>
  </div>
  <div class="field">
    <%= f.label :photos %><br>
    <%= f.text_field :imgs %>
  </div>
  <div class="field">
    <%= f.label :instalink %><br>
    <%= f.text_field :instalink %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bussinesses/edit.html.erb
<h1>Editing Bussiness</h1>

<%= render 'form' %>

<%= link_to 'Show', @bussiness %> |
<%= link_to 'Back', bussinesses_path %>

app/views/bussinesses/index.html.erb
<!-- 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width = device width, initial-scale = 1">

<title>Min Bayti</title>

<body>
<p id="notice"><%= notice %></p>
<style>
@font-face {
font-family: 'Billabong';
font-style: normal;
font-weight: normal;
src: local('Billabong'), url('Billabong.woff') format('woff');
}
img {
	height:200px;
	width:200px;
}
#hamad{
	margin-bottom: 20px;
	text-align: justify;
	line-height: 1.5;
}
.page-header {
	margin-left: 20px;
	color:#ffffff;
	text-align: center;
	font-family: Billabong;
}
body{
	background-image:url("/assets/businesses.jpeg");
	background-size: cover;
	;
}

</style>
</head>

<div class="page-header">
<h1>Instagram Businesses</h1>
</div>
<table class="table table-striped">
  <thead>
   
  </thead>

  <tbody>
    <div class="container">
     <div class="row no-gutters">
    <% @bussinesses.each do |bussiness| %>
      <tr>

	       <div class="col-xs-12 col-sm-8 col-md-8 col-lg-6" id="hamad"> 
	       <div class="media" id="hamad">	  <div class="media-left" id="hamad">
	       <img src=<%= bussiness.photos %> class="media-object">
	       </div>
	       <div class="media-body" id="hamad">
		   <h4 class="media-heading"><%= bussiness.name %></h4>

		   Description:  <%=bussiness.description%><br>
		   Review:  <%= bussiness.reviews %><br>
		   Instalink:  <%= bussiness.instalink %>
		   
		   </div>

	       
			</div>
			</div>
       
      </tr>
    <% end %>

 </div>
 
  </tbody>
</table>
<br>



<%= link_to 'New Bussiness', new_bussiness_path %>
</body>
</html>
-->
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Min Bayti Businesses</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylesheets/3-col-portfolio.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
	body{
			background-image: url(/assets/dark.jpeg);
	}
#s {
    display:block;
    max-width:100%;
    height:auto;
    border-radius:6px;
}
#lower{
    margin-top:40px;
    font-family: verdana, arial, helvetica, sans-serif;
    font-size:10;
}
#forP{
	font-size:14px;
}
.text{
    color:white;
}


</style>
<!--
a:hover{
	color:white;
	background-color:#DAA520;
}
.btn:hover { 
    background-color: #DAA520;

}
.btn{
	border-color:white;
	color:white;
}
-->
</head>

<body>

    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row" id="lower">
            <div class="col-lg-12">
                <h1 class="page-header">Home Businesses
                    <small id="s">in Qatar</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
        <% @bussinesses.each do |bussiness| %>
            <div class="col-md-4 portfolio-item">
                <%=link_to( image_tag(bussiness.imgs, :size => "350x200"), bussiness)%>
                <h3>
                    <%= link_to bussiness.name, bussiness, :class=>"btn btn-default btn-md" %> 
			    <%if !Review.where("bussiness_id like ?", bussiness.id).average(:rating).blank? %>
					<small class="text"><%=Review.where("bussiness_id like ?",bussiness.id).average(:rating).round(2)%></small>
			    <%end%>
				
				
				</h3>
                <p id="forP"><%=bussiness.description%></p>
            </div>
            <%end%>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <hr>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

</body>

</html>

app/views/bussinesses/new.html.erb
<h1>New Bussiness</h1>

<%= render 'form' %>

<%= link_to 'Back', bussinesses_path %>

app/views/bussinesses/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<style>
    body{
        background-image: url(/assets/dark.jpeg);
      padding:50px;
}
  .text{
    color:black;
  }
  #food_item{
    border-top:2px solid #ffffff;
    border-right:2px solid #ffffff;
    margin:10px;
    padding:10px;
    width:250px;
  }
  #name{
    text-decoration: underline;
  }
  #profile{
      padding-top: 50px;
    }
  </style>
</head>
<div class="container">
<body>
  <p id="notice"><%= notice %></p>
  <br><br>
  <h1 class="page-header"><%= @bussiness.name %></h1>
  <div class="container" id="profile">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
        <li data-target="#myCarousel" data-slide-to="6"></li>
        <li data-target="#myCarousel" data-slide-to="7"></li>
      </ol>
      <div class="carousel-inner">
      <div class="item active" align="center">
        <%= image_tag(@bussiness.imgs, :size => "300x286", :align => "center") %>
        </div>
      <%@bussiness.photos.each do |photo|%>
      <!-- Wrapper for slides -->
      
        <div class="item" align="center">
        <%= image_tag(photo.path, :size => "300x286", :align => "center") %>
        </div>
      <%end%>
      </div>
      
      
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    

    <div class="table-responsive">
      <table class="table" >
        <tbody>
          <tr>
            <td><strong>Name:</strong></td>
            <td><%= @bussiness.name %></td>
          </tr>
          <tr>
            <td><strong>Description:</strong></td>
            <td><%= @bussiness.description %></td>
          </tr>
          <tr>
            <td><strong>Reviews</strong></td>
            <td><button class="btn btn-default btn-sm" data-toggle="collapse" data-target="#demo">View Reviews</button>
              <%= link_to "Write Review", new_bussiness_review_path(@bussiness), class: "btn btn-default btn-sm" %>
              <div id="demo" class="collapse">
                <table>
                  <tr>
                    <th>Reviewer</th>
                    <th>Review</th>
                  </tr>
                  <%Review.where("bussiness_id like ?", @bussiness.id).each do |review|%>
                  <tr>
                    <td><%=review.user.fname + " " + review.user.lname%>: </td>
                    <td> <%= review.comment %></td>
                  </tr>
                  <%end%>
                </table>
              </div>
            </td>
          </tr>
          <tr>
            <td><strong>Instalink:</strong></td>
            <td><%=link_to( image_tag("/assets/iglogo.png", :size => "30x30"), @bussiness.instalink)%></td>
          </tr>
          <tr>
            <td><strong>Rating:</strong></td>
            <td><%=Review.where("bussiness_id like ?", @bussiness.id).average(:rating).round(2)%></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <h2>Foods from this home</h2>
  <div class="row">
        <% Food.where("bussiness_id like ?", @bussiness.id).each do |food| %>
            <div class="col-md-2 portfolio-item" id="food_item">
                <h3 id="name"><%=food.name%></h3>
                <p>From: <%=food.bussiness.name%></p>
                <p>Category: <%=food.category.name%></p>
                <%if logged_in? && current_user.admin?%>
                <%= link_to 'Show', food, :class => "btn btn-default" %>
                <%= link_to 'Edit', edit_food_path(food), :class => "btn btn-default" %>
                <%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
                <%= button_to "Add to Cart", orderlines_path(food_id: food), :class => "btn btn-default" %>
            <%elsif logged_in?%>
                <%= button_to "Add to Cart", orderlines_path(food_id: food), :class => "btn btn-default" %>
            <%end%>
            </div>
            <%end%>
  </div>
  <br>
  <div class="form-group row">
    <div class="col-sm-10">

      <%= link_to "Back", bussinesses_path, class: "btn btn-default" %>
    </div>
  </div>
</body>
</div>
</html>