config/routes.rb
Rails.application.routes.draw do
  resources :confirmed_orders
  resources :photos
  resources :reviews
  resources :sessions
  
  
  resources :categories
  resources :foods
  resources :bussinesses
  resources :orders
  resources :orderlines
  resources :users
  
  resources :bussinesses do
      collection do
        get 'search'
      end
      resources :reviews
    end
    
  get 'home/index'
  root :to => "home#index"
  get '/bussinesses' => "bussinesses#index"
  get '/about' => "about#index"
  get 'Login' => 'sessions#new', as: :login
  get 'SignUp' => 'users#new', as: :signup
  post 'SignUp' => 'users#create'
  get 'edit_user' => 'users#show', as: :show

  delete 'visitors/index' => 'sessions#destroy', as: :logout

  resources :users do
        get :make_admin, on: :member
  end

  

end

app/models/bussiness.rb
class Bussiness < ActiveRecord::Base
  has_many :foods 
  belongs_to :user
  has_many :photos
  has_many :reviews
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :foods
end

app/models/confirmed_order.rb
class ConfirmedOrder < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :bussiness
  belongs_to :category 
  def self.search(search)
  	where("category_id LIKE ?","%#{search}")
  end
  def self.search2(search)
  	where("bussiness_id LIKE ?","%#{search}")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
  
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  has_one :order
  belongs_to :confirmed_order
  belongs_to :food
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bussiness
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :bussiness
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bussiness
  has_many :orders
  has_many :reviews
  has_secure_password
  
  validates :fname, :lname,:password,:password_confirmation,  presence: true
  validates_format_of :fname, :lname, with: /\A[A-Z]{1}[a-z]+( +[a-zA-Z]+)*/

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

	before_save { self.email = email.downcase }

  
  validates :password, length: { minimum: 6 }
  

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]


  # GET /foods
  # GET /foods.json
  def index
    if params[:food] and params[:food][:category_id]
      @foods = Food.search(params[:food][:category_id])
    elsif params[:food] and params[:food][:bussiness_id]
      @foods = Food.search2(params[:food][:bussiness_id])
    else
      @foods = Food.all
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private 
  
    def admin_only
      if !current_user.admin?
        redirect_to root_path
      end
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:category_id, :bussiness_id, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bussinesses_helper.rb
module BussinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def current_order
  		Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
	  	order = Order.create
	  	session[:order_id] = order.id
	  	order
  	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
      session[:user_id] = user.id
	end
	
	def current_user
      @current_user ||= User.find_by(id: session[:user_id])
	end
    
    def logged_in?
      !current_user.nil?
	end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "Select Category" %>
  </div>
  <div class="field">
	<%= f.collection_select :bussiness_id, Bussiness.all, :id, :name, :prompt => "Select Business" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>
<style>
    body{
        background-image: url(/assets/dark.jpeg);
      padding:50px;
    }
  .table{
    color:black;
    background-color:white;
  }
  .text{
    color:black;
  }
  #food_item{
    border-top:2px solid #ffffff;
    border-right:2px solid #ffffff;
    margin:10px;
    padding:10px;
    width:250px;
  }
  #filters{
    margin-bottom: 15px;
  }
  #alignment{
    text-align: center;
  }
  #name{
    text-decoration: underline;
  }
  </style>
<div class="container">
<h1 class="page-header">Home Foods</h1>
<div class="row">
<div class="col-md-12 portfolio-item" id="filters">
  <%= form_tag foods_path, :method => 'get' do %>
  <div id="alignment"><%= submit_tag "Show All Foods" , :class=> "btn btn-default btn-lg"%></div>
<% end %>
</div>
<div class="col-md-4 portfolio-item" id="filters">
  <%= form_tag foods_path, :method => 'get' do %>
  <div id="alignment"><%= collection_select :food, :category_id, Category.all, :id, :name, prompt: true %></div><br>
  <div id="alignment"><%= submit_tag "Filter by Category" , :class=> "btn btn-default"%></div>
<% end %>
</div>
<div class="col-md-4 portfolio-item" id="filters">
</div>
<div class="col-md-4 portfolio-item" id="filters">
<%= form_tag foods_path, :method => 'get' do %>
  <div id="alignment"><%= collection_select :food, :bussiness_id, Bussiness.all, :id, :name, prompt: true%></div><br>
  <div id="alignment"><%= submit_tag "Filter by Business" , :class=> "btn btn-default" %></div>
<% end %>
</div>
</div>
  <div class="row">
        <% @foods.each do |food| %>
            <div class="col-md-2 portfolio-item" id="food_item">
                <h3 id="name"><%=food.name%></h3>
                <p>From: <%=food.bussiness.name%></p>
                <p>Category: <%=food.category.name%></p>
                <%if logged_in? && current_user.admin?%>
                <%= link_to 'Show', food, :class => "btn btn-default" %>
                <%= link_to 'Edit', edit_food_path(food), :class => "btn btn-default" %>
                <%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
                <%= button_to "Add to Cart", orderlines_path(food_id: food), :class => "btn btn-default" %>
            <%elsif logged_in?%>
                <%= button_to "Add to Cart", orderlines_path(food_id: food), :class => "btn btn-default" %>
            <%end%>
            </div>
            <%end%>
  </div>
</div>

<br>
  <%if logged_in? && current_user.admin?%>
<%= link_to 'New Food', new_food_path, :class => "btn btn-default btn-lg" %>
 <%end%>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @food.category.name %>
</p>
<p>
  <strong>Business:</strong>
  <%= @food.bussiness.name %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>