config/routes.rb
Rails.application.routes.draw do
  resources :confirmed_orders
  resources :photos
  resources :reviews
  resources :sessions
  
  
  resources :categories
  resources :foods
  resources :bussinesses
  resources :orders
  resources :orderlines
  resources :users
  
  resources :bussinesses do
      collection do
        get 'search'
      end
      resources :reviews
    end
    
  get 'home/index'
  root :to => "home#index"
  get '/bussinesses' => "bussinesses#index"
  get '/about' => "about#index"
  get 'Login' => 'sessions#new', as: :login
  get 'SignUp' => 'users#new', as: :signup
  post 'SignUp' => 'users#create'
  get 'edit_user' => 'users#show', as: :show

  delete 'visitors/index' => 'sessions#destroy', as: :logout

  resources :users do
        get :make_admin, on: :member
  end

  

end

app/models/bussiness.rb
class Bussiness < ActiveRecord::Base
  has_many :foods 
  belongs_to :user
  has_many :photos
  has_many :reviews
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :foods
end

app/models/confirmed_order.rb
class ConfirmedOrder < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :bussiness
  belongs_to :category 
  def self.search(search)
  	where("category_id LIKE ?","%#{search}")
  end
  def self.search2(search)
  	where("bussiness_id LIKE ?","%#{search}")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
  
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  has_one :order
  belongs_to :confirmed_order
  belongs_to :food
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bussiness
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :bussiness
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bussiness
  has_many :orders
  has_many :reviews
  has_secure_password
  
  validates :fname, :lname,:password,:password_confirmation,  presence: true
  validates_format_of :fname, :lname, with: /\A[A-Z]{1}[a-z]+( +[a-zA-Z]+)*/

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

	before_save { self.email = email.downcase }

  
  validates :password, length: { minimum: 6 }
  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @bussiness = Bussiness.find(params[:bussiness_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :user_id, :bussiness_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bussinesses_helper.rb
module BussinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def current_order
  		Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
	  	order = Order.create
	  	session[:order_id] = order.id
	  	order
  	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
      session[:user_id] = user.id
	end
	
	def current_user
      @current_user ||= User.find_by(id: session[:user_id])
	end
    
    def logged_in?
      !current_user.nil?
	end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rating %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
	  <th>Name</th>
	  <th>Business</th>
      <th>Rating</th>
      <th>Comment</th>
	  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
		<td><%= review.user.fname %></td>
		<td><%= review.bussiness.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<!--<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>
-->
<style>
body{
	margin-top: 4%;

	background-image: url(/assets/dark.jpeg);

}
#submity{
	margin-top: 20px;

}
.text{
	color:black;

}
.col-sm-10{
	color:black;
}

</style>
<body>
<div class="row">
<div class="col-lg-12">
	<h1 class="page-header">Write a Review
  	  <small id="s">your opinion matters</small>
    </h1>
</div>
</div>
<div class="container">
<%= form_for([@bussiness, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <%= f.label :rating, class: 'col-sm-4 form-control-label' %>
    <div class="col-sm-10">
      <%= f.number_field :rating, class: 'text' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :comment, class: 'col-sm-4 form-control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :comment , class: 'text' %>
    </div>
  </div>
  
  

  	<%= f.hidden_field :user_id, :value => current_user.id%>
  
	<%= f.hidden_field :bussiness_id, :value => @bussiness.id%>



  <div class="form-group row">
    <div class="col-sm-10" id="submity">
      <%= f.submit 'Submit Your Opinion', class: 'btn btn-default' %>
      <%= link_to "Back", bussinesses_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>
</div>
<body>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user.fname %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>


<%= link_to 'Back', reviews_path %>