config/routes.rb
Rails.application.routes.draw do
  resources :confirmed_orders
  resources :photos
  resources :reviews
  resources :sessions
  
  
  resources :categories
  resources :foods
  resources :bussinesses
  resources :orders
  resources :orderlines
  resources :users
  
  resources :bussinesses do
      collection do
        get 'search'
      end
      resources :reviews
    end
    
  get 'home/index'
  root :to => "home#index"
  get '/bussinesses' => "bussinesses#index"
  get '/about' => "about#index"
  get 'Login' => 'sessions#new', as: :login
  get 'SignUp' => 'users#new', as: :signup
  post 'SignUp' => 'users#create'
  get 'edit_user' => 'users#show', as: :show

  delete 'visitors/index' => 'sessions#destroy', as: :logout

  resources :users do
        get :make_admin, on: :member
  end

  

end

app/models/bussiness.rb
class Bussiness < ActiveRecord::Base
  has_many :foods 
  belongs_to :user
  has_many :photos
  has_many :reviews
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :foods
end

app/models/confirmed_order.rb
class ConfirmedOrder < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :bussiness
  belongs_to :category 
  def self.search(search)
  	where("category_id LIKE ?","%#{search}")
  end
  def self.search2(search)
  	where("bussiness_id LIKE ?","%#{search}")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderlines, dependent: :destroy
  belongs_to :user
  
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  has_one :order
  belongs_to :confirmed_order
  belongs_to :food
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :bussiness
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :bussiness
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bussiness
  has_many :orders
  has_many :reviews
  has_secure_password
  
  validates :fname, :lname,:password,:password_confirmation,  presence: true
  validates_format_of :fname, :lname, with: /\A[A-Z]{1}[a-z]+( +[a-zA-Z]+)*/

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }

	before_save { self.email = email.downcase }

  
  validates :password, length: { minimum: 6 }
  

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def current_order
  		Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
	  	order = Order.create
	  	session[:order_id] = order.id
	  	order
  	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
      session[:user_id] = user.id
	end
	
	def current_user
      @current_user ||= User.find_by(id: session[:user_id])
	end
    
    def logged_in?
      !current_user.nil?
	end
    
    def log_out
      session.delete(:user_id)
      @current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
          <%= render 'layouts/navigation_links_left' %>

          <%= render 'layouts/navigation_links_right' %>

app/views/layouts/_navigation_links_left.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Home', root_path('about') %></li>
<li><%= link_to 'Foods', foods_path%></li>
<li><%= link_to 'Businesses', bussinesses_path%></li>

<%if logged_in? && current_user.admin?%>

 <li><%= link_to 'Users', users_path%></li>
	<li> <%= link_to 'Categories', categories_path %></li>


<%end%>

app/views/layouts/_navigation_links_right.html.erb
	<% if logged_in? %>
		  <li><%= link_to 'My Account', show_path%></li>
	      <li><%= link_to 'Logout', logout_path, method: :delete%></li>
		  <% if session[:order_id].nil? %>
		  <%order = Order.create%>
	      <%session[:order_id] = order.id%>
	  	  <%order%>
		   <li><%= link_to 'My Cart', order_path(Order.find(session[:order_id]))%></li>
		  <% else %>
	  	  <li><%= link_to 'My Cart', order_path(Order.find(session[:order_id]))%></li>
		  <%end%>
	    <% else %>
	      <li><%= link_to 'Login', login_path %></li>
	      <li><%= link_to 'Sign up', signup_path %></li>
	    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MinBayti</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Min Bayti</a>
    </div>
    <ul class="nav navbar-nav">
		<%= render 'layouts/navigation' %>
      
    </ul>
  </div>
</nav>
-->
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link href="/assets/grayscale.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i> <span class="light"></span> Min Bayti
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <%= render 'layouts/navigation' %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
	


<%= yield %>

</body>
</html>